### PR TITLE
MGMT-1694 Fix unit test

### PR DESCRIPTION
**Pull request by empovit**

### CODE REVIEW

**Comment by eranco74** [comment]
@empovit is this still relevant?
https://github.com/eranco74/assisted-installer/pull/91 was merged.

**Comment by empovit** [comment]
@eranco74 yes, it is. It doesn't matter much right now, but will have to change soon.

**Comment by eranco74** [comment]
Please rebase...

**Comment by empovit** [comment]
Doesn't seem to help. Pushing an image fails.

**Comment by eranco74** [comment]
> Doesn't seem to help. Pushing an image fails.

OK, found the issue and fixed it.

**Pull request merged**
