### PR TITLE
Eran/pr images

### PR DESCRIPTION
**Pull request by eranco74**

### CODE REVIEW

**Comment by eranco74** [comment]
Thoughts?

**Comment by ronniel1** [comment]
Just make sure that the PR images will expire in quay.io

**Comment by eranco74** [comment]
https://quay.io/repository/ocpmetal/assisted-installer?tab=tags

**Comment by eranco74** [comment]
https://quay.io/repository/ocpmetal/assisted-installer-controller?tab=tags

**Pull request merged**
